<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WKWIN2371013" failures="2" tests="4" name="Test" time="68.309" errors="0" timestamp="2023-01-20T22:03:57 IST">
  <testcase classname="Tests.LoginTests" name="login" time="6.031"/>
  <testcase classname="Tests.LoginTests" name="login" time="5.772">
    <failure type="java.lang.AssertionError" message="expected [Failure] but found [Success]">
      <![CDATA[java.lang.AssertionError: expected [Failure] but found [Success]
at Tests.LoginTests.login(LoginTests.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="Tests.TwoTests" name="Test1" time="4.171">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at Tests.TwoTests.Test1(TwoTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="Tests.ThreeTests" name="TestThree" time="0.0"/>
</testsuite> <!-- Test -->
